apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-edge-service
  labels:
    app: polar-edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polar-edge-service
  template:
    metadata:
      labels:
        app: polar-edge-service
    spec:
      containers:
        - name: polar-edge-service
          image: polar-edge-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh","-c","sleep 5" ]
          ports:
            - containerPort: 9000
          env:
            - name: CATALOG_SERVICE_URL
              value: http://catalog-service
            - name: ORDER_SERVICE_URL
              value: http://order-service
            - name: SPA_URL
              value: http://polar-ui
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_REDIS_HOST
              value: polar-redis
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: http://polar-keycloak/realms/PolarBookshop